### PR TITLE
ALS-2724 Add OpenTelemetry agent to support X-Ray metric collection

### PR DESCRIPTION
**Pull request by marcus-bcl**
Example of AWS OpenTelemetry / ServiceMap in the `delius-core-dev` environment:

Screenshot 2021-03-26 at 17 19 04

### CODE REVIEW

**Review by smjmoj — COMMENTED** [review]
Looks good to me.
However perhaps we should place these in the S3 Artefacts bucket for longevity?
While it's an AWS project and should be stable we're pulling "latest", might it be safer to always use a version that we know works through the environments?
It's possible a version might be newer in prod and causes issues which you could find difficult to replicate in lower envs?
Same point for the zip file in lives above.

**Comment by marcus-bcl** [comment]
> Looks good to me.
> However perhaps we should place these in the S3 Artefacts bucket for longevity?
> While it's an AWS project and should be stable we're pulling "latest", might it be safer to always use a version that we know works through the environments?
> It's possible a version might be newer in prod and causes issues which you could find difficult to replicate in lower envs?
> Same point for the zip file in lives above.

I'd rather stick with using the latest, as it follows JB's pattern earlier in the file to ensure we always have the latest SSM Agent - which has worked well so far. In the unlikely scenario that the x-ray/telemetry agent install fails for any reason, it won't block the startup or break anything - so it's relatively risk-free.

Happy to be told otherwise, but for non-functional stuff like this I think keeping it simple and up-to-date is a better approach?

**Comment by smjmoj** [comment]
> I'd rather stick with using the latest, as it follows JB's pattern earlier in the file to ensure we always have the latest SSM Agent - which has worked well so far. In the unlikely scenario that the x-ray/telemetry agent install fails for any reason, it won't block the startup or break anything - so it's relatively risk-free.
> 
> Happy to be told otherwise, but for non-functional stuff like this I think keeping it simple and up-to-date is a better approach?

OK, the ami is AWS latest as is the remainder - so ok go for it.
Probably more reliable than certain other vendors that change URL and name formats at the drop of a  hat .

**Review by smjmoj — APPROVED** [review]
LGTM

**Pull request merged**
